###
# @name List all Categories
GET {{host}}/hackathon/{{hackathon_id}}/categories

###
# @name Create Category
POST {{host}}/category
Content-Type: application/json

{
  "title": "Form over Function",
  "description": "This is for the horrible \"projects\" which are actually just flashy presentations that always win",
  "hackathonId": "{{hackathon_id}}"
}

###
# @name Edit Category
PUT {{host}}/category/{{category_id}}
Content-Type: application/json

{
  "title": "Renamed Category",
  "description": "This is now very different from what it was before!!!"
}

###
# @name Get Category
GET {{host}}/category/{{category_id}}

###
# @name Remove Category
DELETE {{host}}/category/{{category_id}}
