###
# @name List all Hackathons
GET {{host}}/hackathons

###
# @name Create Hackathon
POST {{host}}/hackathon
Content-Type: application/json

{
  "title": "Hackweek2022",
  "startDate": "2022-09-01",
  "endDate": "2022-09-05"
}

###
# @name Edit Hackathon
PUT {{host}}/hackathon/{{hackathon_id}}
Content-Type: application/json

{
  "title": "Renamed Hackathon",
  "startDate": "2022-11-23",
  "endDate": "2022-11-22"
}

###
# @name Get Hackathon
GET {{host}}/hackathon/{{hackathon_id}}

###
# @name Remove Hackathon
DELETE {{host}}/hackathon/{{hackathon_id}}
