###
# @name List all Hackathons
GET {{host}}/restapis/{{api_id}}/local/_user_request_/hackathons

###
# @name Create Hackathon
POST {{host}}/restapis/{{api_id}}/local/_user_request_/hackathon
Content-Type: application/json

{
  "title": "some future hackweek",
  "startDate": "2023-09-01",
  "endDate": "2023-09-05"
}

###
# @name Create Hackathon
POST {{host}}/restapis/{{api_id}}/local/_user_request_/hackathon
Content-Type: application/json

{
  "title": "comeon",
  "startDate": "2022-09-03",
  "endDate": "2022-09-08"
}

###
# @name Get Hackathon
GET {{host}}/restapis/{{api_id}}/local/_user_request_/hackathon/{{hackathon_id}}

###
# @name Remove Hackathon
DELETE {{host}}/restapis/{{api_id}}/local/_user_request_/hackathon/{{hackathon_id}}
