###
# @name List all Ideas
GET {{host}}/restapis/{{api_id}}/local/_user_request_/hackathon/{{hackathon_id}}/ideas

###
# @name Create Idea
POST {{host}}/restapis/{{api_id}}/local/_user_request_/idea
Content-Type: application/json

{
  "ownerId": "...",
  "hackathonId": "f6081e81-7805-4e67-bc79-8c7c118b8212",
  "participantIds": [
    "..."
  ],
  "title": "no errors anymore",
  "description": "finaly make everything working",
  "problem": "errors",
  "goal": "no errors",
  "requiredSkills": [
    "..."
  ],
  "categoryId": "..."
}

###
# @name Get Idea
GET {{host}}/restapis/{{api_id}}/local/_user_request_/idea/{{idea_id}}

###
# @name Remove Idea
DELETE {{host}}/restapis/{{api_id}}/local/_user_request_/idea/{{idea_id}}
