###
# @name List all Ideas
GET {{host}}/hackathon/{{hackathon_id}}/ideas

###
# @name Create Idea
POST {{host}}/idea
Content-Type: application/json

{
  "ownerId": "{{participant_id}}",
  "hackathonId": "{{hackathon_id}}",
  "title": "Wicked awesome idea",
  "description": "By doing all the things and being the greatest of all time hackathons can be great again",
  "problem": "Hackathons have become weak and boring",
  "goal": "Make hackathons great again",
  "requiredSkills": [
    "{{skill_id}}"
  ],
  "categoryId": "{{category_id}}"
}

###
# @name Edit Idea
PUT {{host}}/idea/{{idea_id}}
Content-Type: application/json

{
  "title": "SUPER BORING IDEA",
  "description": "We're actually just going to do nothing.  No work, no coding, no presentation... nothing...",
  "problem": "Too much goes on all the time, we should take it easy",
  "goal": "Make hackathons relaxed again",
  "requiredSkills": [
    "{{skill_id_2}}"
  ],
  "categoryId": "{{category_id_2}}"
}

###
# @name Join Idea
PUT {{host}}/restapis/{{api_id}}/local/_user_request_/idea/{{idea_id}}/join/{{participant_id}}

###
# @name Get Idea
GET {{host}}/idea/{{idea_id}}

###
# @name Remove Idea
DELETE {{host}}/idea/{{idea_id}}
