###
# @name List all Participants
GET {{host}}/restapis/{{api_id}}/local/_user_request_/hackathon/{{hackathon_id}}/participants

###
# @name Create Participant
POST {{host}}/restapis/{{api_id}}/local/_user_request_/participant
Content-Type: application/json

{
  "userId": "{{user_id}}",
  "hackathonId": "{{hackathon_id}}"
}

###
# @name Get Participant
GET {{host}}/restapis/{{api_id}}/local/_user_request_/participant/{{participant_id}}

###
# @name Remove Participant
DELETE {{host}}/restapis/{{api_id}}/local/_user_request_/participant/e27fb873-fd63-4c43-a00b-4593a3662953
