###
# @name List all Participants
GET {{host}}/hackathon/{{hackathon_id}}/participants

###
# @name Create Participant
POST {{host}}/participant
Content-Type: application/json

{
  "userId": "{{user_id}}",
  "hackathonId": "{{hackathon_id}}"
}

###
# @name Get Participant
GET {{host}}/participant/{{participant_id}}

###
# @name Remove Participant
DELETE {{host}}/participant/{{participant_id}}
