###
# @name List all Skills
GET {{host}}/restapis/{{api_id}}/local/_user_request_/skills

###
# @name Create Skill
POST {{host}}/restapis/{{api_id}}/local/_user_request_/skill
Content-Type: application/json

{
  "name": "video games",
  "description": "I'm basically a pro gamer"
}

###
# @name Edit Skill
PUT {{host}}/restapis/{{api_id}}/local/_user_request_/skill/{{skill_id}}
Content-Type: application/json

{
  "name": "Chess",
  "description": "It's a sport!"
}

###
# @name Get Skill
GET {{host}}/restapis/{{api_id}}/local/_user_request_/skill/{{skill_id}}

###
# @name Remove Skill
DELETE {{host}}/restapis/{{api_id}}/local/_user_request_/skill/{{skill_id}}
