###
# @name List all Users
GET {{host}}/users

###
# @name Create User
POST {{host}}/user
Content-Type: application/json

{
  "lastName": "Musterdude",
  "firstName": "Matthew",
  "emailAddress": "musty.matt@inter.net",
  "roles": ["Participant"],
  "skills": ["{{skill_id}}"],
  "imageUrl": "https://images.unsplash.com/photo-1608889825205-eebdb9fc5806?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880"
}

###
# @name Edit User
PUT {{host}}/user/{{user_id}}
Content-Type: application/json

{
  "lastName": "Doe",
  "firstName": "Jane",
  "skills": ["{{skill_id}}","{{skill_id_2}}"],
  "imageUrl": "https://images.unsplash.com/photo-1634926878768-2a5b3c42f139?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=756"
}

###
# @name Get User
GET {{host}}/user/{{user_id}}

###
# @name Remove User
DELETE {{host}}/user/{{user_id}}
