export default [
  {
    id: 0,
    title: 'aaa idea 1',
    description: 'really a good idea ',
    favNumber: 1,
    reason: 'my reason was...',
    problem: 'it solve this and this problem',
    goal: 'the goal for the hackweek is...',
    skills: 'usefull skills are:',
    category: 'testdata',
    participants: 'me and myself',
    aws: 'need aws yes/no',
  },
  {
    id: 1,
    title: 'aab idea 2',
    description: 'just a better idea ',
    favNumber: 3,
    reason: 'my reason was...',
    problem: 'it solve this and this problem',
    goal: 'the goal for the hackweek is...',
    skills: 'usefull skills are:',
    category: 'testdata',
    participants: 'me and myself',
    aws: 'need aws yes/no',
  },
  {
    id: 2,
    title: 'abb idea 3',
    description: 'absolute the best idea in the world ',
    favNumber: 4,
    reason: 'my reason was...',
    problem: 'it solve this and this problem',
    goal: 'the goal for the hackweek is...',
    skills: 'usefull skills are:',
    category: 'testdata',
    participants: 'me and myself',
    aws: 'need aws yes/no',
  },
  {
    id: 3,
    title: 'bbb idea 4',
    description: 'absolute the best idea in the world ',
    favNumber: 6,
    reason: 'my reason was...',
    problem: 'it solve this and this problem',
    goal: 'the goal for the hackweek is...',
    skills: 'usefull skills are:',
    category: 'testdata',
    participants: 'me and myself',
    aws: 'need aws yes/no',
  },
  {
    id: 4,
    title: 'bbc idea 5',
    description: 'absolute the best idea in the world ',
    favNumber: 7,
    reason: 'my reason was...',
    problem: 'it solve this and this problem',
    goal: 'the goal for the hackweek is...',
    skills: 'usefull skills are:',
    category: 'testdata',
    participants: 'me and myself',
    aws: 'need aws yes/no',
  },
  {
    id: 5,
    title: 'bcc idea 6',
    description: 'absolute the best idea in the world ',
    favNumber: 9,
    reason: 'my reason was...',
    problem: 'it solve this and this problem',
    goal: 'the goal for the hackweek is...',
    skills: 'usefull skills are:',
    category: 'testdata',
    participants: 'me and myself',
    aws: 'need aws yes/no',
  },
  {
    id: 6,
    title: 'ccc idea 7',
    description: 'absolute the best idea in the world ',
    favNumber: 10,
    reason: 'my reason was...',
    problem: 'it solve this and this problem',
    goal: 'the goal for the hackweek is...',
    skills: 'usefull skills are:',
    category: 'testdata',
    participants: 'me and myself',
    aws: 'need aws yes/no',
  },
  {
    id: 7,
    title: 'cca idea 8',
    description: 'absolute the best idea in the world ',
    favNumber: 12,
    reason: 'my reason was...',
    problem: 'it solve this and this problem',
    goal: 'the goal for the hackweek is...',
    skills: 'usefull skills are:',
    category: 'testdata',
    participants: 'me and myself',
    aws: 'need aws yes/no',
  },
  {
    id: 8,
    title: 'caa idea 9',
    description: 'absolute the best idea in the world ',
    favNumber: 13,
    reason: 'my reason was...',
    problem: 'it solve this and this problem',
    goal: 'the goal for the hackweek is...',
    skills: 'usefull skills are:',
    category: 'testdata',
    participants: 'me and myself',
    aws: 'need aws yes/no',
  },
  {
    id: 9,
    title: 'abc idea 10',
    description: 'absolute the best idea in the world ',
    favNumber: 15,
    reason: 'my reason was...',
    problem: 'it solve this and this problem',
    goal: 'the goal for the hackweek is...',
    skills: 'usefull skills are:',
    category: 'testdata',
    participants: 'me and myself',
    aws: 'need aws yes/no',
  },
]
