export default [
  {
    id: 1,
    titel: 'idea 1',
    description: 'really a good idea ',
    favNumber: 2,
    reason: 'my reason was...',
    problem: 'it solve this and this problem',
    goal: 'the goal for the hackweek is...',
    skills: 'usefull skills are:',
    category: 'testdata',
    participants: 'me and myself',
    aws: 'need aws yes/no',
  },
  {
    id: 2,
    titel: 'idea 2',
    description: 'just a better idea ',
    favNumber: 8,
    reason: 'my reason was...',
    problem: 'it solve this and this problem',
    goal: 'the goal for the hackweek is...',
    skills: 'usefull skills are:',
    category: 'testdata',
    participants: 'me and myself',
    aws: 'need aws yes/no',
  },
  {
    id: 3,
    titel: 'idea 3',
    description: 'absolute the best idea in the world ',
    favNumber: 5,
    reason: 'my reason was...',
    problem: 'it solve this and this problem',
    goal: 'the goal for the hackweek is...',
    skills: 'usefull skills are:',
    category: 'testdata',
    participants: 'me and myself',
    aws: 'need aws yes/no',
  },
]
